name: Deploy Flutter Portfolio to GitHub Pages

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Flutter 🐦
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies 📦
        run: flutter pub get

      - name: Build for web ⚙️
        run: flutter build web --release --base-href "/portfolio/" --web-renderer canvaskit

      - name: Upload artifact 📦
        # Automatically uploads an artifact from the build folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web

  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
